name: Refresh Relay Targets

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  Refresh:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash -el {0}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: fetch clash yaml
        run: |
          wget "${{ secrets.RELAY_TARGETS_URL }}" --user-agent "${{  secrets.USER_AGENT }}" -O clash.yaml

      - name: upload clash yaml to gist
        run: | 
          gh gist edit ${{ secrets.GIST_ID }} -f clash.yaml clash.yaml