name: Refresh Relay Targets

on:
  workflow_dispatch:
  schedule:
    - cron: "35 1 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  Refresh:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash -el {0}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull the docker image of subconverter and setup local subconverter instance
        run: |
          docker pull yaoyinying/subconverter
          docker run -d --restart=always --name  subconverter -p 25500:25500 yaoyinying/subconverter:latest
          
      - name: fetch clash yaml
        run: |
          RELAY_TARGETS_URL_LOCAL=$(echo "${{ secrets.RELAY_TARGETS_URL }}" |  sed -r 's/http[s]?:\/+[a-z-]+\.[a-z-]+\.[a-z-]+/http:\/\/localhost:25500/')
          wget "$RELAY_TARGETS_URL_LOCAL" --user-agent "mihomo.party/v1.7.3 (clash.meta)" -O clash.yaml

      - name: upload clash yaml to gist
        env:
          GH_TOKEN: ${{ secrets.GIST_PAT }}
        run: | 
          gh gist edit ${{ secrets.GIST_ID }} -f clash.yaml clash.yaml
